### ISSUE TITLE
`plugins.list` Format

### ISSUE THREAD

**Issue by drasko** [mainflux/emqttd-docker#4]
Is this space-separated list or each plugin can be written in new line?

Also, are there plugins that do not have to be downloaded (i.e. already contained in original emqttd distribution)?

**Comment by mijicd** [comment]
The file is structured as plugin per line. There are a couple of plugins available with EMQTT distribution (e.g dashboard, mysql auth).

**Comment by drasko** [comment]
This (one per line) should be noted in the README. Thanks for the info, I am closing the issue.
